UI_TEXT = {
    "English": {
        "title": "Multilingual Funding Intelligence System",
        "caption": "AI-powered funding, investor & policy intelligence for founders",
        "features": "Features",
        "choose_feature": "Choose a feature",
        "language": "Language",
        "select_language": "Select language",
        "ask_question": "Ask your question",
        "submit": "Submit",
        "thinking": "Expert is thinking...",
        "eligibility": "Eligibility Check",
        "regional": "Regional Funding",
        "trends": "Funding Trends",
        "policy": "Policy Simplifier",
        "investor": "Investor Interest",
        "rejection": "Common Rejection Reasons",
        "state": "State",
        "sector": "Sector",
        "revenue_stage": "Revenue stage",
        "upload_policy": "Upload policy document (PDF)"
    },

    "Malayalam": {
        "title": "ബഹുഭാഷാ ഫണ്ടിംഗ് ഇന്റലിജൻസ് സിസ്റ്റം",
        "caption": "സ്ഥാപകർക്ക് വേണ്ടി എഐ അധിഷ്ഠിത ഫണ്ടിംഗ്, നിക്ഷേപക, നയ വിവരങ്ങൾ",
        "features": "സവിശേഷതകൾ",
        "choose_feature": "ഒരു സവിശേഷത തിരഞ്ഞെടുക്കുക",
        "language": "ഭാഷ",
        "select_language": "ഭാഷ തിരഞ്ഞെടുക്കുക",
        "ask_question": "നിങ്ങളുടെ ചോദ്യം എഴുതുക",
        "submit": "സമർപ്പിക്കുക",
        "thinking": "ഫണ്ടർ ആലോചിക്കുന്നു...",
        "eligibility": "യോഗ്യത പരിശോധിക്കുക",
        "regional": "പ്രാദേശിക ഫണ്ടിംഗ്",
        "trends": "ഫണ്ടിംഗ് പ്രവണതകൾ",
        "policy": "നയ ലളിതീകരണം",
        "investor": "നിക്ഷേപക താൽപര്യം",
        "rejection": "പൊതുവായ നിരസണ കാരണങ്ങൾ",
        "state": "സംസ്ഥാനം",
        "sector": "മേഖല",
        "revenue_stage": "വരുമാന ഘട്ടം",
        "upload_policy": "നയ ഡോക്യുമെന്റ് അപ്‌ലോഡ് ചെയ്യുക (PDF)"
    },

    "Hindi": {
        "title": "बहुभाषी फंडिंग इंटेलिजेंस सिस्टम",
        "caption": "संस्थापकों के लिए एआई-संचालित फंडिंग, निवेशक और नीति जानकारी",
        "features": "विशेषताएँ",
        "choose_feature": "एक विशेषता चुनें",
        "language": "भाषा",
        "select_language": "भाषा चुनें",
        "ask_question": "अपना प्रश्न पूछें",
        "submit": "जमा करें",
        "thinking": " फंडर सोच रहा है...",
        "eligibility": "योग्यता जांच",
        "regional": "क्षेत्रीय फंडिंग",
        "trends": "फंडिंग रुझान",
        "policy": "नीति सरलीकरण",
        "investor": "निवेशक रुचि",
        "rejection": "सामान्य अस्वीकृति कारण",
        "state": "राज्य",
        "sector": "क्षेत्र",
        "revenue_stage": "राजस्व चरण",
        "upload_policy": "नीति दस्तावेज़ अपलोड करें (PDF)"
    }
}
